ARG BASE_IMAGE
FROM ${BASE_IMAGE}
ARG APPLICATION_NAME
WORKDIR /$APPLICATION_NAME

FROM scratch

COPY --from=0 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
ADD ./local_bin/coredns-arm64 /coredns

EXPOSE 53 53/udp
ENTRYPOINT ["/coredns"]